export const MOODS = {
  OVERJOYED: {
    id: 'Overjoyed',
    label: 'Overjoyed',
    emoji: '🥰',
    score: 10,
    color: 'yellow',
    prompt: 'What wonderful things happened today?',
    pixabayQuery: 'joyful+celebration+happy',
  },
  HAPPY: {
    id: 'Happy',
    label: 'Happy',
    emoji: '🌞',
    score: 9,
    color: 'lightyellow',
    prompt: 'What made you smile today?',
    pixabayQuery: 'smile+sunshine+bright',
  },
  GRATEFUL: {
    id: 'Grateful',
    label: 'Grateful',
    emoji: '🧸',
    score: 8,
    color: 'gold',
    prompt: 'What are you thankful for today?',
    pixabayQuery: 'gratitude+sunset+peace',
  },
  CONTENT: {
    id: 'Content',
    label: 'Content',
    emoji: '🍃',
    score: 7,
    color: 'lightgreen',
    prompt: 'What brought you peace today?',
    pixabayQuery: 'calm+peaceful+relax',
  },
  INSPIRED: {
    id: 'Inspired',
    label: 'Inspired',
    emoji: '🌟',
    score: 8,
    color: 'skyblue',
    prompt: 'What sparked your creativity?',
    pixabayQuery: 'inspiration+light+idea',
  },
  RELAXED: {
    id: 'Relaxed',
    label: 'Relaxed',
    emoji: '🫧',
    score: 7,
    color: 'teal',
    prompt: 'What helped you unwind today?',
    pixabayQuery: 'relaxation+calm+peaceful',
  },
  MOTIVATED: {
    id: 'Motivated',
    label: 'Motivated',
    emoji: '🚀',
    score: 8,
    color: 'orange',
    prompt: 'What are you ready to tackle?',
    pixabayQuery: 'motivation+drive+focus',
  },
  EXCITED: {
    id: 'Excited',
    label: 'Excited',
    emoji: '🐣',
    score: 9,
    color: 'hotpink',
    prompt: 'What has you looking forward to tomorrow?',
    pixabayQuery: 'excitement+energy+fun',
  },
  LOVED: {
    id: 'Loved',
    label: 'Loved',
    emoji: '💗',
    score: 9,
    color: 'red',
    prompt: 'Who made you feel loved today?',
    pixabayQuery: 'love+affection+heart',
  },
  OPTIMISTIC: {
    id: 'Optimistic',
    label: 'Optimistic',
    emoji: '🐥',
    score: 8,
    color: 'lightblue',
    prompt: 'What are you hopeful about?',
    pixabayQuery: 'hope+rainbow+future',
  },
  PEACEFUL: {
    id: 'Peaceful',
    label: 'Peaceful',
    emoji: '🌸',
    score: 7,
    color: 'white',
    prompt: 'What helped you feel calm today?',
    pixabayQuery: 'peace+stillness+meditation',
  },
  FOCUSED: {
    id: 'Focused',
    label: 'Focused',
    emoji: '🧠',
    score: 7,
    color: 'navy',
    prompt: 'What were you able to concentrate on today?',
    pixabayQuery: 'focus+productivity+study',
  },
  CURIOUS: {
    id: 'Curious',
    label: 'Curious',
    emoji: '🐾',
    score: 6,
    color: 'limegreen',
    prompt: 'What made you curious today?',
    pixabayQuery: 'curiosity+learning+exploration',
  },
  PLAYFUL: {
    id: 'Playful',
    label: 'Playful',
    emoji: '🧃',
    score: 7,
    color: 'coral',
    prompt: 'What fun or games did you enjoy?',
    pixabayQuery: 'fun+games+laughter',
  },
  SILLY: {
    id: 'Silly',
    label: 'Silly',
    emoji: '🍭',
    score: 6,
    color: 'lightcoral',
    prompt: 'What made you laugh today?',
    pixabayQuery: 'silly+funny+goofy',
  },
  SAD: {
    id: 'Sad',
    label: 'Sad',
    emoji: '🌧️',
    score: 2,
    color: 'blue',
    prompt: 'What’s been weighing on you today?',
    pixabayQuery: 'sad+rain+lonely',
  },
  LONELY: {
    id: 'Lonely',
    label: 'Lonely',
    emoji: '🪐',
    score: 2,
    color: 'slategray',
    prompt: 'What made you feel isolated today?',
    pixabayQuery: 'lonely+alone+quiet',
  },
  ANXIOUS: {
    id: 'Anxious',
    label: 'Anxious',
    emoji: '🫨',
    score: 3,
    color: 'lightgray',
    prompt: 'What’s been on your mind lately?',
    pixabayQuery: 'anxiety+stress+worry',
  },
  TIRED: {
    id: 'Tired',
    label: 'Tired',
    emoji: '💤',
    score: 3,
    color: 'gray',
    prompt: 'What drained your energy today?',
    pixabayQuery: 'tired+rest+sleep',
  },
  ANGRY: {
    id: 'Angry',
    label: 'Angry',
    emoji: '🧨',
    score: 1,
    color: 'darkred',
    prompt: 'What made you upset today?',
    pixabayQuery: 'anger+frustration+explosion',
  }
};

export const getMoodById = (moodId) => {
    return MOODS[moodId.toUpperCase()]
}